//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSACSoft.ProductosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", ConfigurationName="ProductosWS.ProductosWS")]
    public interface ProductosWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/ProductosWS/helloRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/ProductosWS/helloResponse")]
        ARSACSoft.ProductosWS.helloResponse hello(ARSACSoft.ProductosWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/ProductosWS/helloRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/ProductosWS/helloResponse")]
        System.Threading.Tasks.Task<ARSACSoft.ProductosWS.helloResponse> helloAsync(ARSACSoft.ProductosWS.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        public ARSACSoft.ProductosWS.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(ARSACSoft.ProductosWS.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        public ARSACSoft.ProductosWS.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(ARSACSoft.ProductosWS.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductosWSChannel : ARSACSoft.ProductosWS.ProductosWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosWSClient : System.ServiceModel.ClientBase<ARSACSoft.ProductosWS.ProductosWS>, ARSACSoft.ProductosWS.ProductosWS {
        
        public ProductosWSClient() {
        }
        
        public ProductosWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.ProductosWS.helloResponse ARSACSoft.ProductosWS.ProductosWS.hello(ARSACSoft.ProductosWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ARSACSoft.ProductosWS.helloRequest inValue = new ARSACSoft.ProductosWS.helloRequest();
            inValue.Body = new ARSACSoft.ProductosWS.helloRequestBody();
            inValue.Body.name = name;
            ARSACSoft.ProductosWS.helloResponse retVal = ((ARSACSoft.ProductosWS.ProductosWS)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.ProductosWS.helloResponse> ARSACSoft.ProductosWS.ProductosWS.helloAsync(ARSACSoft.ProductosWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.ProductosWS.helloResponse> helloAsync(string name) {
            ARSACSoft.ProductosWS.helloRequest inValue = new ARSACSoft.ProductosWS.helloRequest();
            inValue.Body = new ARSACSoft.ProductosWS.helloRequestBody();
            inValue.Body.name = name;
            return ((ARSACSoft.ProductosWS.ProductosWS)(this)).helloAsync(inValue);
        }
    }
}
