//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSACSoft.SedeWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", ConfigurationName="SedeWS.SedesWS")]
    public interface SedesWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/insertarOrdenDeAbastecimientoReques" +
            "t", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/insertarOrdenDeAbastecimientoRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoResponse insertarOrdenDeAbastecimiento(ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/insertarOrdenDeAbastecimientoReques" +
            "t", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/insertarOrdenDeAbastecimientoRespon" +
            "se")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoResponse> insertarOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/entregarOrdenDeAbastecimientoReques" +
            "t", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/entregarOrdenDeAbastecimientoRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoResponse entregarOrdenDeAbastecimiento(ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/entregarOrdenDeAbastecimientoReques" +
            "t", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/entregarOrdenDeAbastecimientoRespon" +
            "se")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoResponse> entregarOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/obtenerStockDeProductoEnSedeRequest" +
            "", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/obtenerStockDeProductoEnSedeRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeResponse obtenerStockDeProductoEnSede(ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/obtenerStockDeProductoEnSedeRequest" +
            "", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/obtenerStockDeProductoEnSedeRespons" +
            "e")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeResponse> obtenerStockDeProductoEnSedeAsync(ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/cancelarOrdenDeAbastecimientoReques" +
            "t", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/cancelarOrdenDeAbastecimientoRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoResponse cancelarOrdenDeAbastecimiento(ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/cancelarOrdenDeAbastecimientoReques" +
            "t", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/cancelarOrdenDeAbastecimientoRespon" +
            "se")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoResponse> cancelarOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/verificarEntregaDeOrdenDeAbastecimi" +
            "entoRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/verificarEntregaDeOrdenDeAbastecimi" +
            "entoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoResponse verificarEntregaDeOrdenDeAbastecimiento(ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/verificarEntregaDeOrdenDeAbastecimi" +
            "entoRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/verificarEntregaDeOrdenDeAbastecimi" +
            "entoResponse")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoResponse> verificarEntregaDeOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarOrdenesDeAbastecimientoPorIdE" +
            "mpleadoEstadoRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarOrdenesDeAbastecimientoPorIdE" +
            "mpleadoEstadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoResponse listarOrdenesDeAbastecimientoPorIdEmpleadoEstado(ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarOrdenesDeAbastecimientoPorIdE" +
            "mpleadoEstadoRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarOrdenesDeAbastecimientoPorIdE" +
            "mpleadoEstadoResponse")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoResponse> listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoAsync(ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/obtenerStockDeProductoEnSedePrincip" +
            "alRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/obtenerStockDeProductoEnSedePrincip" +
            "alResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalResponse obtenerStockDeProductoEnSedePrincipal(ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/obtenerStockDeProductoEnSedePrincip" +
            "alRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/obtenerStockDeProductoEnSedePrincip" +
            "alResponse")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalResponse> obtenerStockDeProductoEnSedePrincipalAsync(ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarLineasDeOrdenDeAbastecimiento" +
            "Request", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarLineasDeOrdenDeAbastecimiento" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoResponse listarLineasDeOrdenDeAbastecimiento(ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarLineasDeOrdenDeAbastecimiento" +
            "Request", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarLineasDeOrdenDeAbastecimiento" +
            "Response")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoResponse> listarLineasDeOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarProductosDeSedePorNombreMarca" +
            "CategoriaRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarProductosDeSedePorNombreMarca" +
            "CategoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaResponse listarProductosDeSedePorNombreMarcaCategoria(ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarProductosDeSedePorNombreMarca" +
            "CategoriaRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarProductosDeSedePorNombreMarca" +
            "CategoriaResponse")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaResponse> listarProductosDeSedePorNombreMarcaCategoriaAsync(ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarSedesRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarSedesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.listarSedesResponse listarSedes(ARSACSoft.SedeWS.listarSedesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarSedesRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarSedesResponse")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarSedesResponse> listarSedesAsync(ARSACSoft.SedeWS.listarSedesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/modificarSedeRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/modificarSedeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.modificarSedeResponse modificarSede(ARSACSoft.SedeWS.modificarSedeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/modificarSedeRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/modificarSedeResponse")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.modificarSedeResponse> modificarSedeAsync(ARSACSoft.SedeWS.modificarSedeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/insertarSedeRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/insertarSedeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.insertarSedeResponse insertarSede(ARSACSoft.SedeWS.insertarSedeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/insertarSedeRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/insertarSedeResponse")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.insertarSedeResponse> insertarSedeAsync(ARSACSoft.SedeWS.insertarSedeRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarProductosDeSedeRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarProductosDeSedeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ARSACSoft.SedeWS.listarProductosDeSedeResponse listarProductosDeSede(ARSACSoft.SedeWS.listarProductosDeSedeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarProductosDeSedeRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/SedesWS/listarProductosDeSedeResponse")]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarProductosDeSedeResponse> listarProductosDeSedeAsync(ARSACSoft.SedeWS.listarProductosDeSedeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/")]
    public partial class ordenDeAbastecimiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string estadoField;
        
        private System.DateTime fechaCancelacionField;
        
        private bool fechaCancelacionFieldSpecified;
        
        private System.DateTime fechaEntregaField;
        
        private bool fechaEntregaFieldSpecified;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private int idEmpleadoField;
        
        private int idOrdenDeAbastecimientoField;
        
        private lineaOrdenDeAbastecimiento[] lineasField;
        
        private sede sedeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaCancelacion {
            get {
                return this.fechaCancelacionField;
            }
            set {
                this.fechaCancelacionField = value;
                this.RaisePropertyChanged("fechaCancelacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCancelacionSpecified {
            get {
                return this.fechaCancelacionFieldSpecified;
            }
            set {
                this.fechaCancelacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCancelacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
                this.RaisePropertyChanged("fechaEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEntregaSpecified {
            get {
                return this.fechaEntregaFieldSpecified;
            }
            set {
                this.fechaEntregaFieldSpecified = value;
                this.RaisePropertyChanged("fechaEntregaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                this.idEmpleadoField = value;
                this.RaisePropertyChanged("idEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idOrdenDeAbastecimiento {
            get {
                return this.idOrdenDeAbastecimientoField;
            }
            set {
                this.idOrdenDeAbastecimientoField = value;
                this.RaisePropertyChanged("idOrdenDeAbastecimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public lineaOrdenDeAbastecimiento[] lineas {
            get {
                return this.lineasField;
            }
            set {
                this.lineasField = value;
                this.RaisePropertyChanged("lineas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public sede sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/")]
    public partial class lineaOrdenDeAbastecimiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int cantidadField;
        
        private int idLineaOrdenDeAbastecimientoField;
        
        private producto productoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idLineaOrdenDeAbastecimiento {
            get {
                return this.idLineaOrdenDeAbastecimientoField;
            }
            set {
                this.idLineaOrdenDeAbastecimientoField = value;
                this.RaisePropertyChanged("idLineaOrdenDeAbastecimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private categoria categoriaField;
        
        private byte[] fotoField;
        
        private int idProductoField;
        
        private marca marcaField;
        
        private string nombreField;
        
        private double precioPorMayorField;
        
        private double precioPorMenorField;
        
        private promocion promocionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public categoria categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public marca marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double precioPorMayor {
            get {
                return this.precioPorMayorField;
            }
            set {
                this.precioPorMayorField = value;
                this.RaisePropertyChanged("precioPorMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double precioPorMenor {
            get {
                return this.precioPorMenorField;
            }
            set {
                this.precioPorMenorField = value;
                this.RaisePropertyChanged("precioPorMenor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public promocion promocion {
            get {
                return this.promocionField;
            }
            set {
                this.promocionField = value;
                this.RaisePropertyChanged("promocion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/")]
    public partial class categoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idCategoriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                this.idCategoriaField = value;
                this.RaisePropertyChanged("idCategoria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/")]
    public partial class sedeXProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private producto productoField;
        
        private int stockField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/")]
    public partial class sede : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoField;
        
        private string direccionField;
        
        private bool esPrincipalField;
        
        private int idSedeField;
        
        private sedeXProducto[] productosField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool esPrincipal {
            get {
                return this.esPrincipalField;
            }
            set {
                this.esPrincipalField = value;
                this.RaisePropertyChanged("esPrincipal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idSede {
            get {
                return this.idSedeField;
            }
            set {
                this.idSedeField = value;
                this.RaisePropertyChanged("idSede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("productos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public sedeXProducto[] productos {
            get {
                return this.productosField;
            }
            set {
                this.productosField = value;
                this.RaisePropertyChanged("productos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/")]
    public partial class promocion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int cantidadminimaField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idPromocionField;
        
        private double porcentajeField;
        
        private producto productoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadminima {
            get {
                return this.cantidadminimaField;
            }
            set {
                this.cantidadminimaField = value;
                this.RaisePropertyChanged("cantidadminima");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPromocion {
            get {
                return this.idPromocionField;
            }
            set {
                this.idPromocionField = value;
                this.RaisePropertyChanged("idPromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double porcentaje {
            get {
                return this.porcentajeField;
            }
            set {
                this.porcentajeField = value;
                this.RaisePropertyChanged("porcentaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/")]
    public partial class marca : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idMarcaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idMarca {
            get {
                return this.idMarcaField;
            }
            set {
                this.idMarcaField = value;
                this.RaisePropertyChanged("idMarca");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOrdenDeAbastecimiento", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarOrdenDeAbastecimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ARSACSoft.SedeWS.ordenDeAbastecimiento arg0;
        
        public insertarOrdenDeAbastecimientoRequest() {
        }
        
        public insertarOrdenDeAbastecimientoRequest(ARSACSoft.SedeWS.ordenDeAbastecimiento arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOrdenDeAbastecimientoResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarOrdenDeAbastecimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarOrdenDeAbastecimientoResponse() {
        }
        
        public insertarOrdenDeAbastecimientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="entregarOrdenDeAbastecimiento", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class entregarOrdenDeAbastecimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ARSACSoft.SedeWS.ordenDeAbastecimiento arg0;
        
        public entregarOrdenDeAbastecimientoRequest() {
        }
        
        public entregarOrdenDeAbastecimientoRequest(ARSACSoft.SedeWS.ordenDeAbastecimiento arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="entregarOrdenDeAbastecimientoResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class entregarOrdenDeAbastecimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public entregarOrdenDeAbastecimientoResponse() {
        }
        
        public entregarOrdenDeAbastecimientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerStockDeProductoEnSede", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerStockDeProductoEnSedeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public obtenerStockDeProductoEnSedeRequest() {
        }
        
        public obtenerStockDeProductoEnSedeRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerStockDeProductoEnSedeResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerStockDeProductoEnSedeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public obtenerStockDeProductoEnSedeResponse() {
        }
        
        public obtenerStockDeProductoEnSedeResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarOrdenDeAbastecimiento", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class cancelarOrdenDeAbastecimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public cancelarOrdenDeAbastecimientoRequest() {
        }
        
        public cancelarOrdenDeAbastecimientoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarOrdenDeAbastecimientoResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class cancelarOrdenDeAbastecimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public cancelarOrdenDeAbastecimientoResponse() {
        }
        
        public cancelarOrdenDeAbastecimientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarEntregaDeOrdenDeAbastecimiento", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class verificarEntregaDeOrdenDeAbastecimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ARSACSoft.SedeWS.ordenDeAbastecimiento arg0;
        
        public verificarEntregaDeOrdenDeAbastecimientoRequest() {
        }
        
        public verificarEntregaDeOrdenDeAbastecimientoRequest(ARSACSoft.SedeWS.ordenDeAbastecimiento arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarEntregaDeOrdenDeAbastecimientoResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class verificarEntregaDeOrdenDeAbastecimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public verificarEntregaDeOrdenDeAbastecimientoResponse() {
        }
        
        public verificarEntregaDeOrdenDeAbastecimientoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesDeAbastecimientoPorIdEmpleadoEstado", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoRequest() {
        }
        
        public listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoRequest(int arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ARSACSoft.SedeWS.ordenDeAbastecimiento[] @return;
        
        public listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoResponse() {
        }
        
        public listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoResponse(ARSACSoft.SedeWS.ordenDeAbastecimiento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerStockDeProductoEnSedePrincipal", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerStockDeProductoEnSedePrincipalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public obtenerStockDeProductoEnSedePrincipalRequest() {
        }
        
        public obtenerStockDeProductoEnSedePrincipalRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerStockDeProductoEnSedePrincipalResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerStockDeProductoEnSedePrincipalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public obtenerStockDeProductoEnSedePrincipalResponse() {
        }
        
        public obtenerStockDeProductoEnSedePrincipalResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarLineasDeOrdenDeAbastecimiento", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarLineasDeOrdenDeAbastecimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public listarLineasDeOrdenDeAbastecimientoRequest() {
        }
        
        public listarLineasDeOrdenDeAbastecimientoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarLineasDeOrdenDeAbastecimientoResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarLineasDeOrdenDeAbastecimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ARSACSoft.SedeWS.lineaOrdenDeAbastecimiento[] @return;
        
        public listarLineasDeOrdenDeAbastecimientoResponse() {
        }
        
        public listarLineasDeOrdenDeAbastecimientoResponse(ARSACSoft.SedeWS.lineaOrdenDeAbastecimiento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosDeSedePorNombreMarcaCategoria", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosDeSedePorNombreMarcaCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg3;
        
        public listarProductosDeSedePorNombreMarcaCategoriaRequest() {
        }
        
        public listarProductosDeSedePorNombreMarcaCategoriaRequest(int arg0, string arg1, int arg2, int arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosDeSedePorNombreMarcaCategoriaResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosDeSedePorNombreMarcaCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ARSACSoft.SedeWS.sedeXProducto[] @return;
        
        public listarProductosDeSedePorNombreMarcaCategoriaResponse() {
        }
        
        public listarProductosDeSedePorNombreMarcaCategoriaResponse(ARSACSoft.SedeWS.sedeXProducto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSedes", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarSedesRequest {
        
        public listarSedesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSedesResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarSedesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ARSACSoft.SedeWS.sede[] @return;
        
        public listarSedesResponse() {
        }
        
        public listarSedesResponse(ARSACSoft.SedeWS.sede[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarSede", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarSedeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ARSACSoft.SedeWS.sede arg0;
        
        public modificarSedeRequest() {
        }
        
        public modificarSedeRequest(ARSACSoft.SedeWS.sede arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarSedeResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarSedeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarSedeResponse() {
        }
        
        public modificarSedeResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSede", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSedeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ARSACSoft.SedeWS.sede arg0;
        
        public insertarSedeRequest() {
        }
        
        public insertarSedeRequest(ARSACSoft.SedeWS.sede arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSedeResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSedeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarSedeResponse() {
        }
        
        public insertarSedeResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosDeSede", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosDeSedeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public listarProductosDeSedeRequest() {
        }
        
        public listarProductosDeSedeRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosDeSedeResponse", WrapperNamespace="http://services.arsacsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosDeSedeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ARSACSoft.SedeWS.sedeXProducto[] @return;
        
        public listarProductosDeSedeResponse() {
        }
        
        public listarProductosDeSedeResponse(ARSACSoft.SedeWS.sedeXProducto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SedesWSChannel : ARSACSoft.SedeWS.SedesWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SedesWSClient : System.ServiceModel.ClientBase<ARSACSoft.SedeWS.SedesWS>, ARSACSoft.SedeWS.SedesWS {
        
        public SedesWSClient() {
        }
        
        public SedesWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SedesWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SedesWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SedesWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoResponse ARSACSoft.SedeWS.SedesWS.insertarOrdenDeAbastecimiento(ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoRequest request) {
            return base.Channel.insertarOrdenDeAbastecimiento(request);
        }
        
        public int insertarOrdenDeAbastecimiento(ARSACSoft.SedeWS.ordenDeAbastecimiento arg0) {
            ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoRequest inValue = new ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoRequest();
            inValue.arg0 = arg0;
            ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).insertarOrdenDeAbastecimiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoResponse> ARSACSoft.SedeWS.SedesWS.insertarOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoRequest request) {
            return base.Channel.insertarOrdenDeAbastecimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoResponse> insertarOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.ordenDeAbastecimiento arg0) {
            ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoRequest inValue = new ARSACSoft.SedeWS.insertarOrdenDeAbastecimientoRequest();
            inValue.arg0 = arg0;
            return ((ARSACSoft.SedeWS.SedesWS)(this)).insertarOrdenDeAbastecimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoResponse ARSACSoft.SedeWS.SedesWS.entregarOrdenDeAbastecimiento(ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoRequest request) {
            return base.Channel.entregarOrdenDeAbastecimiento(request);
        }
        
        public int entregarOrdenDeAbastecimiento(ARSACSoft.SedeWS.ordenDeAbastecimiento arg0) {
            ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoRequest inValue = new ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoRequest();
            inValue.arg0 = arg0;
            ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).entregarOrdenDeAbastecimiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoResponse> ARSACSoft.SedeWS.SedesWS.entregarOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoRequest request) {
            return base.Channel.entregarOrdenDeAbastecimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoResponse> entregarOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.ordenDeAbastecimiento arg0) {
            ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoRequest inValue = new ARSACSoft.SedeWS.entregarOrdenDeAbastecimientoRequest();
            inValue.arg0 = arg0;
            return ((ARSACSoft.SedeWS.SedesWS)(this)).entregarOrdenDeAbastecimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeResponse ARSACSoft.SedeWS.SedesWS.obtenerStockDeProductoEnSede(ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeRequest request) {
            return base.Channel.obtenerStockDeProductoEnSede(request);
        }
        
        public int obtenerStockDeProductoEnSede(int arg0, int arg1) {
            ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeRequest inValue = new ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).obtenerStockDeProductoEnSede(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeResponse> ARSACSoft.SedeWS.SedesWS.obtenerStockDeProductoEnSedeAsync(ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeRequest request) {
            return base.Channel.obtenerStockDeProductoEnSedeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeResponse> obtenerStockDeProductoEnSedeAsync(int arg0, int arg1) {
            ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeRequest inValue = new ARSACSoft.SedeWS.obtenerStockDeProductoEnSedeRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ARSACSoft.SedeWS.SedesWS)(this)).obtenerStockDeProductoEnSedeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoResponse ARSACSoft.SedeWS.SedesWS.cancelarOrdenDeAbastecimiento(ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoRequest request) {
            return base.Channel.cancelarOrdenDeAbastecimiento(request);
        }
        
        public int cancelarOrdenDeAbastecimiento(int arg0) {
            ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoRequest inValue = new ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoRequest();
            inValue.arg0 = arg0;
            ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).cancelarOrdenDeAbastecimiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoResponse> ARSACSoft.SedeWS.SedesWS.cancelarOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoRequest request) {
            return base.Channel.cancelarOrdenDeAbastecimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoResponse> cancelarOrdenDeAbastecimientoAsync(int arg0) {
            ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoRequest inValue = new ARSACSoft.SedeWS.cancelarOrdenDeAbastecimientoRequest();
            inValue.arg0 = arg0;
            return ((ARSACSoft.SedeWS.SedesWS)(this)).cancelarOrdenDeAbastecimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoResponse ARSACSoft.SedeWS.SedesWS.verificarEntregaDeOrdenDeAbastecimiento(ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoRequest request) {
            return base.Channel.verificarEntregaDeOrdenDeAbastecimiento(request);
        }
        
        public int verificarEntregaDeOrdenDeAbastecimiento(ARSACSoft.SedeWS.ordenDeAbastecimiento arg0) {
            ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoRequest inValue = new ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoRequest();
            inValue.arg0 = arg0;
            ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).verificarEntregaDeOrdenDeAbastecimiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoResponse> ARSACSoft.SedeWS.SedesWS.verificarEntregaDeOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoRequest request) {
            return base.Channel.verificarEntregaDeOrdenDeAbastecimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoResponse> verificarEntregaDeOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.ordenDeAbastecimiento arg0) {
            ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoRequest inValue = new ARSACSoft.SedeWS.verificarEntregaDeOrdenDeAbastecimientoRequest();
            inValue.arg0 = arg0;
            return ((ARSACSoft.SedeWS.SedesWS)(this)).verificarEntregaDeOrdenDeAbastecimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoResponse ARSACSoft.SedeWS.SedesWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstado(ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoRequest request) {
            return base.Channel.listarOrdenesDeAbastecimientoPorIdEmpleadoEstado(request);
        }
        
        public ARSACSoft.SedeWS.ordenDeAbastecimiento[] listarOrdenesDeAbastecimientoPorIdEmpleadoEstado(int arg0, string arg1) {
            ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoRequest inValue = new ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).listarOrdenesDeAbastecimientoPorIdEmpleadoEstado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoResponse> ARSACSoft.SedeWS.SedesWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoAsync(ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoRequest request) {
            return base.Channel.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoResponse> listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoAsync(int arg0, string arg1) {
            ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoRequest inValue = new ARSACSoft.SedeWS.listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ARSACSoft.SedeWS.SedesWS)(this)).listarOrdenesDeAbastecimientoPorIdEmpleadoEstadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalResponse ARSACSoft.SedeWS.SedesWS.obtenerStockDeProductoEnSedePrincipal(ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalRequest request) {
            return base.Channel.obtenerStockDeProductoEnSedePrincipal(request);
        }
        
        public int obtenerStockDeProductoEnSedePrincipal(int arg0) {
            ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalRequest inValue = new ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalRequest();
            inValue.arg0 = arg0;
            ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).obtenerStockDeProductoEnSedePrincipal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalResponse> ARSACSoft.SedeWS.SedesWS.obtenerStockDeProductoEnSedePrincipalAsync(ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalRequest request) {
            return base.Channel.obtenerStockDeProductoEnSedePrincipalAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalResponse> obtenerStockDeProductoEnSedePrincipalAsync(int arg0) {
            ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalRequest inValue = new ARSACSoft.SedeWS.obtenerStockDeProductoEnSedePrincipalRequest();
            inValue.arg0 = arg0;
            return ((ARSACSoft.SedeWS.SedesWS)(this)).obtenerStockDeProductoEnSedePrincipalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoResponse ARSACSoft.SedeWS.SedesWS.listarLineasDeOrdenDeAbastecimiento(ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoRequest request) {
            return base.Channel.listarLineasDeOrdenDeAbastecimiento(request);
        }
        
        public ARSACSoft.SedeWS.lineaOrdenDeAbastecimiento[] listarLineasDeOrdenDeAbastecimiento(int arg0) {
            ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoRequest inValue = new ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoRequest();
            inValue.arg0 = arg0;
            ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).listarLineasDeOrdenDeAbastecimiento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoResponse> ARSACSoft.SedeWS.SedesWS.listarLineasDeOrdenDeAbastecimientoAsync(ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoRequest request) {
            return base.Channel.listarLineasDeOrdenDeAbastecimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoResponse> listarLineasDeOrdenDeAbastecimientoAsync(int arg0) {
            ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoRequest inValue = new ARSACSoft.SedeWS.listarLineasDeOrdenDeAbastecimientoRequest();
            inValue.arg0 = arg0;
            return ((ARSACSoft.SedeWS.SedesWS)(this)).listarLineasDeOrdenDeAbastecimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaResponse ARSACSoft.SedeWS.SedesWS.listarProductosDeSedePorNombreMarcaCategoria(ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaRequest request) {
            return base.Channel.listarProductosDeSedePorNombreMarcaCategoria(request);
        }
        
        public ARSACSoft.SedeWS.sedeXProducto[] listarProductosDeSedePorNombreMarcaCategoria(int arg0, string arg1, int arg2, int arg3) {
            ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaRequest inValue = new ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).listarProductosDeSedePorNombreMarcaCategoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaResponse> ARSACSoft.SedeWS.SedesWS.listarProductosDeSedePorNombreMarcaCategoriaAsync(ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaRequest request) {
            return base.Channel.listarProductosDeSedePorNombreMarcaCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaResponse> listarProductosDeSedePorNombreMarcaCategoriaAsync(int arg0, string arg1, int arg2, int arg3) {
            ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaRequest inValue = new ARSACSoft.SedeWS.listarProductosDeSedePorNombreMarcaCategoriaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((ARSACSoft.SedeWS.SedesWS)(this)).listarProductosDeSedePorNombreMarcaCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.listarSedesResponse ARSACSoft.SedeWS.SedesWS.listarSedes(ARSACSoft.SedeWS.listarSedesRequest request) {
            return base.Channel.listarSedes(request);
        }
        
        public ARSACSoft.SedeWS.sede[] listarSedes() {
            ARSACSoft.SedeWS.listarSedesRequest inValue = new ARSACSoft.SedeWS.listarSedesRequest();
            ARSACSoft.SedeWS.listarSedesResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).listarSedes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarSedesResponse> ARSACSoft.SedeWS.SedesWS.listarSedesAsync(ARSACSoft.SedeWS.listarSedesRequest request) {
            return base.Channel.listarSedesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarSedesResponse> listarSedesAsync() {
            ARSACSoft.SedeWS.listarSedesRequest inValue = new ARSACSoft.SedeWS.listarSedesRequest();
            return ((ARSACSoft.SedeWS.SedesWS)(this)).listarSedesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.modificarSedeResponse ARSACSoft.SedeWS.SedesWS.modificarSede(ARSACSoft.SedeWS.modificarSedeRequest request) {
            return base.Channel.modificarSede(request);
        }
        
        public int modificarSede(ARSACSoft.SedeWS.sede arg0) {
            ARSACSoft.SedeWS.modificarSedeRequest inValue = new ARSACSoft.SedeWS.modificarSedeRequest();
            inValue.arg0 = arg0;
            ARSACSoft.SedeWS.modificarSedeResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).modificarSede(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.modificarSedeResponse> ARSACSoft.SedeWS.SedesWS.modificarSedeAsync(ARSACSoft.SedeWS.modificarSedeRequest request) {
            return base.Channel.modificarSedeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.modificarSedeResponse> modificarSedeAsync(ARSACSoft.SedeWS.sede arg0) {
            ARSACSoft.SedeWS.modificarSedeRequest inValue = new ARSACSoft.SedeWS.modificarSedeRequest();
            inValue.arg0 = arg0;
            return ((ARSACSoft.SedeWS.SedesWS)(this)).modificarSedeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.insertarSedeResponse ARSACSoft.SedeWS.SedesWS.insertarSede(ARSACSoft.SedeWS.insertarSedeRequest request) {
            return base.Channel.insertarSede(request);
        }
        
        public int insertarSede(ARSACSoft.SedeWS.sede arg0) {
            ARSACSoft.SedeWS.insertarSedeRequest inValue = new ARSACSoft.SedeWS.insertarSedeRequest();
            inValue.arg0 = arg0;
            ARSACSoft.SedeWS.insertarSedeResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).insertarSede(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.insertarSedeResponse> ARSACSoft.SedeWS.SedesWS.insertarSedeAsync(ARSACSoft.SedeWS.insertarSedeRequest request) {
            return base.Channel.insertarSedeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.insertarSedeResponse> insertarSedeAsync(ARSACSoft.SedeWS.sede arg0) {
            ARSACSoft.SedeWS.insertarSedeRequest inValue = new ARSACSoft.SedeWS.insertarSedeRequest();
            inValue.arg0 = arg0;
            return ((ARSACSoft.SedeWS.SedesWS)(this)).insertarSedeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.SedeWS.listarProductosDeSedeResponse ARSACSoft.SedeWS.SedesWS.listarProductosDeSede(ARSACSoft.SedeWS.listarProductosDeSedeRequest request) {
            return base.Channel.listarProductosDeSede(request);
        }
        
        public ARSACSoft.SedeWS.sedeXProducto[] listarProductosDeSede(int arg0) {
            ARSACSoft.SedeWS.listarProductosDeSedeRequest inValue = new ARSACSoft.SedeWS.listarProductosDeSedeRequest();
            inValue.arg0 = arg0;
            ARSACSoft.SedeWS.listarProductosDeSedeResponse retVal = ((ARSACSoft.SedeWS.SedesWS)(this)).listarProductosDeSede(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarProductosDeSedeResponse> ARSACSoft.SedeWS.SedesWS.listarProductosDeSedeAsync(ARSACSoft.SedeWS.listarProductosDeSedeRequest request) {
            return base.Channel.listarProductosDeSedeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.SedeWS.listarProductosDeSedeResponse> listarProductosDeSedeAsync(int arg0) {
            ARSACSoft.SedeWS.listarProductosDeSedeRequest inValue = new ARSACSoft.SedeWS.listarProductosDeSedeRequest();
            inValue.arg0 = arg0;
            return ((ARSACSoft.SedeWS.SedesWS)(this)).listarProductosDeSedeAsync(inValue);
        }
    }
}
