//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSACSoft.AlmacenWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.arsacsoft.pucp.edu.pe/", ConfigurationName="AlmacenWS.AlmacenWS")]
    public interface AlmacenWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/AlmacenWS/helloRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/AlmacenWS/helloResponse")]
        ARSACSoft.AlmacenWS.helloResponse hello(ARSACSoft.AlmacenWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.arsacsoft.pucp.edu.pe/AlmacenWS/helloRequest", ReplyAction="http://services.arsacsoft.pucp.edu.pe/AlmacenWS/helloResponse")]
        System.Threading.Tasks.Task<ARSACSoft.AlmacenWS.helloResponse> helloAsync(ARSACSoft.AlmacenWS.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        public ARSACSoft.AlmacenWS.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(ARSACSoft.AlmacenWS.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://services.arsacsoft.pucp.edu.pe/", Order=0)]
        public ARSACSoft.AlmacenWS.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(ARSACSoft.AlmacenWS.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlmacenWSChannel : ARSACSoft.AlmacenWS.AlmacenWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmacenWSClient : System.ServiceModel.ClientBase<ARSACSoft.AlmacenWS.AlmacenWS>, ARSACSoft.AlmacenWS.AlmacenWS {
        
        public AlmacenWSClient() {
        }
        
        public AlmacenWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmacenWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARSACSoft.AlmacenWS.helloResponse ARSACSoft.AlmacenWS.AlmacenWS.hello(ARSACSoft.AlmacenWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ARSACSoft.AlmacenWS.helloRequest inValue = new ARSACSoft.AlmacenWS.helloRequest();
            inValue.Body = new ARSACSoft.AlmacenWS.helloRequestBody();
            inValue.Body.name = name;
            ARSACSoft.AlmacenWS.helloResponse retVal = ((ARSACSoft.AlmacenWS.AlmacenWS)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARSACSoft.AlmacenWS.helloResponse> ARSACSoft.AlmacenWS.AlmacenWS.helloAsync(ARSACSoft.AlmacenWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARSACSoft.AlmacenWS.helloResponse> helloAsync(string name) {
            ARSACSoft.AlmacenWS.helloRequest inValue = new ARSACSoft.AlmacenWS.helloRequest();
            inValue.Body = new ARSACSoft.AlmacenWS.helloRequestBody();
            inValue.Body.name = name;
            return ((ARSACSoft.AlmacenWS.AlmacenWS)(this)).helloAsync(inValue);
        }
    }
}
